# Generated by Django 4.1 on 2022-09-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=40)),
                ('Last_Name', models.CharField(max_length=40)),
                ('Gender', models.CharField(max_length=7)),
                ('Date_of_Birth', models.DateField()),
                ('Mobile_Number', models.IntegerField()),
                ('E_Mail', models.EmailField(max_length=254)),
                ('Adm_Num_and_Date', models.CharField(max_length=60)),
                ('deptmt', models.CharField(max_length=255)),
                ('Father_name', models.CharField(max_length=40)),
                ('Mother_name', models.CharField(max_length=40)),
                ('Father_mob', models.BigIntegerField()),
                ('Mother_mob', models.BigIntegerField()),
                ('Address', models.CharField(max_length=300)),
            ],
        ),
    ]
