# Generated by Django 4.1 on 2022-09-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Mobile_Number',
            field=models.BigIntegerField(),
        ),
    ]
