# Generated by Django 4.1 on 2022-09-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0002_alter_student_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Photo',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
