# Generated by Django 4.1 on 2022-09-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0005_rename_user_photo_student_user_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='User_Photos',
            new_name='User_Photo',
        ),
    ]
